apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: intemo-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.9.0  # <- Update this to a supported Kafka version
  replicas: 1
  bootstrapServers: a78c2e269a9f54f54b42891cb7d9f493-995104c0e4215b73.elb.ap-south-1.amazonaws.com:9094
  config:
    group.id: connect-cluster
    config.storage.topic: connect-cluster-configs
    offset.storage.topic: connect-cluster-offsets
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    output:
      type: docker
      image: stephenz07/mong-deb:2.5
      pushSecret: regcred
    plugins:
      - name: debezium-mongodb-connector
        artifacts:
          - type: tgz
            url: "https://repo1.maven.org/maven2/io/debezium/debezium-connector-mongodb/2.5.0.Final/debezium-connector-mongodb-2.5.0.Final-plugin.tar.gz"
