apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics
  namespace: kafka
  labels:
    app: kafka-metrics
spec:
  selector:
    strimzi.io/name: staging-metrics-intemo-kafka-cluster-kafka
  ports:
    - name: metrics
      port: 9404
      targetPort: 9404
