apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: intemo-connect-cluster
  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.4.0
  image: docker.io/intemo/connect-debezium:latest
  replicas: 1
  bootstrapServers: a9fadbb7f2adf4cfd95d443a5f29cac3-d158e8a8cafe8556.elb.ap-south-1.amazonaws.com:9094
  #tls:
  #  trustedCertificates:
  #    - secretName: my-cluster-cluster-ca-cert
  #      certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                  - matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - kafka
 