apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics-monitor
  namespace: monitoring
  labels:
    release: kube-prom  # This must match your Prometheus release label
spec:
  selector:
    matchLabels:
      app: kafka-metrics
  namespaceSelector:
    matchNames:
      - kafka
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
