apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: staging-metrics-intemo-kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    template:
      externalBootstrapService:
        metadata:
          annotations:
            # NLB Support
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
      perPodService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        # authentication:
        #   type: tls
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: persistent-claim
      size: 8Gi
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 2Gi
    resources:
      requests:
        cpu: 30m
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 150m
          memory: 128Mi
        limits:
          cpu: 350m