apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-health-check-trackings
  labels:
    strimzi.io/cluster: intemo-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: postgres-test-db.cn7xvgq4xmpi.ap-south-1.rds.amazonaws.com
    database.port: "5432"
    database.user: "postgres"
    database.password: "postgres"
    database.dbname: intemo
    database.server.name: health
    topic.prefix: health
    table.include.list: intemo_dev.awb_details
    plugin.name: pgoutput
    topic.creation.default.replication.factor: -1
    topic.creation.default.partitions: 1
    slot.name : "scrapinghealthcheck"
  