# mongodb-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: init-mongodb
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo:5.0
          command:
            - "mongo"
            - "--eval"
            - |
              rs.initiate({
                _id: "rs0",
                members: [{ _id: 0, host: "mongodb-0.mongodb:27017" }]
              });
      restartPolicy: OnFailure
