apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  # IMPORTANT: Change this password to something secure!
  MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
  MONGO_INITDB_ROOT_PASSWORD: "Intemo2023!"