apiVersion: v1
kind: Service
metadata:
  name: intemo-mail-erp-bot
  namespace: default
  labels:
    app: intemo-mail-erp-bot
spec:
  selector:
    app: intemo-mail-erp-bot
  ports:
  - name: http1
    protocol: TCP
    port: 5900
    targetPort: 5900
  - name: http2
    protocol: TCP
    port: 1504
    targetPort: 1504
  - name: http3
    protocol: TCP
    port: 6080
    targetPort: 6080
  type: NodePort