apiVersion: apps/v1
kind: Deployment
metadata:
  name: intemo-erp-bot
  namespace: default
  labels:
    app: intemo-erp-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intemo-erp-bot
  template:
    metadata:
      labels:
        app: intemo-erp-bot
    spec:
      containers:
        - name: intemo-erp-bot
          image: 885876711116.dkr.ecr.ap-south-1.amazonaws.com/intemo-erp-bot-main:erp-bot243202511259
          ports:
            - name: http
              containerPort: 5900
          imagePullPolicy: Always