apiVersion: v1
kind: Service
metadata:
  name: mail-frontend-service
  namespace: default
  labels:
    app: staging-mail-frontend-service
  annotations:
spec:
  selector:
    app: mail-bot-frontend-app
  ports:
  - name: tcp
    port: 7015
    targetPort: 7015
  type: NodePort