apiVersion: apps/v1
kind: Deployment
metadata:
  name: intemo-mail-bot
  namespace: default
  labels:
    app: intemo-mail-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intemo-mail-bot
  template:
    metadata:
      labels:
        app: intemo-mail-bot
    spec:
      containers:
        - name: intemo-mail-bot
          image: 885876711116.dkr.ecr.ap-south-1.amazonaws.com/intemo-mail-bot-main:intemo-mail-bot-backend25320255529
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: Always