apiVersion: batch/v1
kind: CronJob
metadata:
  name: bot-scheduler
spec:
  schedule: "*/1 * * * *"                     # Runs every 5 mins
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1                         # Only 1 retry if it fails
      template:
        spec:
          terminationGracePeriodSeconds: 15  # Graceful shutdown timeout
          restartPolicy: Never
          containers:
            - name: bot-scheduler
              image: 885876711116.dkr.ecr.ap-south-1.amazonaws.com/intemo-erp-bot-main:bot-scheduler304202555959
              imagePullPolicy: Always
          imagePullSecrets:
            - name: regcred                     # Optional: For private ECR access
