apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.metrics.intemo.tech
  name: control-plane-ap-south-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250211
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - ap-south-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops.metrics.intemo.tech
  name: nodes-ap-south-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20250211
  machineType: t3a.medium
  maxSize: 3
  minSize: 1
  role: Node
  nodeLabels:
    app: node-backend
  subnets:
  - ap-south-1a

