apiVersion: v1
kind: Service
metadata:
  name: trackingpostgres
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  labels:
    app: trackingpostgres
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: trackingpostgres