apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    dubug
        Parsers_File parsers.conf

    @INCLUDE input.conf
    @INCLUDE filter.conf
    @INCLUDE output.conf

  input.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Read_from_head    true
        Refresh_Interval  10
        DB                /buffers/flb_kube.db

  filter.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        Kube_Tag_Prefix     kube.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name                grep
        Match               kube.*
        Regex               kubernetes.labels.app    ^(intemo-mail-erp-bot|intemo-mail-bot|mail-bot-frontend-app)$

  output.conf: |
    [OUTPUT]
        Name               s3
        Match              *
        bucket             metrics-staging-logs
        region             ap-south-1
        total_file_size    5M
        upload_timeout     30m
        store_dir          /buffers
        s3_key_format      /logs/intemo-mail-erp-bot/%Y/%m/%d/%H/%M/%S-$UUID.gz
        compression        gzip

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
